### ISSUE TITLE
Usage Consent UI

### ISSUE THREAD

**Issue by DaytonG** [oregondesignservices/MorphicLiteClientWindows#21]
Need to make a simple UI for agreeing to use countly for tracking usage

**Comment by kaspermarkus** [comment]
Language to come from Ben Isacson, morphic DPO

**Comment by nachochris** [comment]
This will be in the EULA. We will have a statement that "aggregated and anonymous usage stats are collected to assist our developers as the develop our code. No private data, data access or any other personal information is gathered or accessible".
