### ISSUE TITLE
Native code to support Night Mode

### ISSUE THREAD

**Issue by owenpshaw** [oregondesignservices/MorphicLiteClientWindows#23]
Research what, if anything, can by done with generic handlers like System Settings, Registry, or SPI.  Implement custom code if necessary.

**Comment by christopher-rtf** [comment]
In MacOS, this feature is called "Night Shift" in the user interface and is labeled a "Blue Light" feature internally.

I reverse-engineered the CoreBrightness's (macOS private framework's) CBBlueLight class, and I implemented get and set functions for all Night Shift ("Night Mode") settings from the Solutions Registry target list.

Submitted via PR 26.
https://github.com/oregondesignservices/MorphicLiteClientMac/pull/26
