### ISSUE TITLE
Add Accept Eula" dialog and EULA to the installer.

### ISSUE THREAD

**Issue by nachochris** [oregondesignservices/MorphicLiteClientWindows#60]
Link to the EULA is here. https://docs.google.com/document/d/1cw0-9UZvSrf9b0Rc9EbHCfxJuMCVXU9NeetqyQWAnqY/edit?usp=sharing

Need to get dialog button (read/accept EULA) in the installer

**Comment by nachochris** [comment]
Just a note that we will have to have this in place prior to allowing folks to download and run the application

**Comment by DaytonG** [comment]
Closed via https://github.com/oregondesignservices/MorphicLiteClientWindows/pull/71
