### ISSUE TITLE
UI Suggestion - Review and Prioritize

### ISSUE THREAD

**Issue by nachochris** [oregondesignservices/MorphicLiteClientWindows#61]
Drew from Oxide had the following list of UI observations and suggestions, Need to review, determine which ones should go into product and make assignments to do so:

1. The lighter green used on some of the buttons only hits a 2.65:1 contrast ratio, which doesn't meet any WCAG accessibility guidelines. Might be something worth looking into to make sure you're fully buttoned-up on the accessibility front.

2. I'm not sure if it's the font selection, or maybe an anti-aliasing issue, but the type labels above the buttons seem particularly hard to read. I think it's possible that this particular typeface — especially bolded — doesn't have great legibility: the counters are very small and the letterforms tend to squish together.

3. In addition to the large "tool tip" pop-up in the middle of the screen, it'd be helpful to have some kind of "hover state" on the actual button a user is mousing over — an outline, a color shift, just something to help a user confirm easily which button their mouse pointer is over.

4. As it stands, there's no indication whatsoever about what "state" the on/off settings are in. For example, users should be able to tell at a glance if the Screen Reader setting is "on" or "off". (In fact, many interfaces now default to removing the button that would change to the setting you're already on. That is, if High Contrast is already on, the user doesn't need to see the "on" button at all, because it's already on.) This applies to "mute" as well — there's no visual indication of whether mute is applied or not.

5. Related to #4, it seems like we have an opportunity to make the text in the pop-up tool tips more dynamic. Maybe it could tell me what relative size the text is at, or what the relative volume level is. Perhaps it could tell me that the high contrast setting is already on. Let's make the messaging as situation-specific as possible.

**Comment by owenpshaw** [comment]
1. Done in #66 
2. Pretty sure I went with the bolded default windows font.  Happy to adjust.
3. Open to hover state, but we need to verify that kind of visual change is accessibility friendly (I don’t think Morphic Classic had it).  Probably low priority since we do have the tooltip on hover.
4. Their recommendation is how I’d normally do a UI, but Gregg specifically cautioned against having buttons change.
5. Agreed #16 is already on the list

**Comment by owenpshaw** [comment]
For now we're keeping the font as-is, not adding a hover state, keeping separate buttons, but implementing #16
